### ISSUE TITLE
Create test to ensure that dashboard datatable data matches required structure

### ISSUE THREAD

**Issue by GuillermoFloresV** [freeCodeCamp/classroom#329] opened 2023-06-04 08:09 UTC
Our dashtable needs three different sources (classroomId, certifications, studentData) of data to render correctly. We should make some assertions to make sure that our data fits the structure that the dashtable requires to render correctly.

We can leverage some of the [expect](https://jestjs.io/docs/expect) functions in Jest to validate the data that we are feeding into the dashboard.

**Comment by ShubhamPatilsd** [comment] 2023-06-08 14:44
CodeDay Labs students will be working on this

**Comment by sihambyte** [comment] 2023-06-30 21:26
Hi @GuillermoFloresV,
Can you give us an example of what the expected data looks like?

**Comment by GuillermoFloresV** [comment] 2023-07-02 19:07
@sihambyte @ShubhamPatilsd 

Hi,

Are you both in the same CodeDay Labs group? @\sihambyte , if you are not we would appreciate it if we left this issue to @\ShubhamPatilsd and their team. 

I'm sorry, I misspoke regarding the issue at hand. We need to write tests that ensure that our dashboard is getting the data that it needs when we are attempting to render it. I will be rewriting the description to fit this new issue, if you have any questions please feel free to ping me or email me.

First, I would like to make sure that you know about incoming changes to the way our initial student data will be structured. This change allows us to have multiple certifications inside of our response. There is a chance that the new data format is not in the mock JSON file during your time at CodeDay so please feel free to continue using the current data. I simply wanted to make a note of this just in case we are ready to push those changes during your time with us. If you are interested in the new data format take a look [here](https://gist.github.com/GuillermoFloresV/7dbe1abada7babc69b626d47b8e23247).

Our dashboard currently expects 3 forms of data: certifications, studentData, classroomId. These are needed to make the dashboard object. We can take a look at the necessary data format in this [gist](https://gist.github.com/GuillermoFloresV/f0c7d79312cccc5e5934944211e901a0).

Again, if you have any questions please feel free to ping me or email me, sorry again for any confusion.

**Comment by ShubhamPatilsd** [comment] 2023-07-02 23:13
They can take over, I'm the Open Source Lead working on CodeDay Labs 😅

**Comment by theGaryLarson** [comment] 2023-08-02 06:05
I updated the snapshot for this test to fit with @ngillux most recent update in PR #421  that was merged 3 hours ago.
![image](https://github.com/freeCodeCamp/classroom/assets/64063020/e644fe05-25d9-470c-902d-1e45ba4effe6)

Its worth noting that the fail was due to a subtle difference between the actual result 
 `title="Last completion time: 9/17/2018, 6:01:46 PM"`

and the result stored in the snapshot
`title="Last completion time: 9/17/2018, 11:01:46 AM"`

The first has a regular space character between 46 and AM.
The second uses a narrow no break space (NNBSP)

This varies from locale and other factors and is caused by using Date.toLocaleString()  in components/StudentActivity line 18.

**Closed** 2023-08-29 00:18 UTC
